name: "SupportDocs Generator"
on:
    push:
        branches:
            - main
jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v2
            - name: Setup Python 3.8.6
              uses: actions/setup-python@v1
              with:
                  python-version: "3.9.5"
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip python-frontmatter
            - name: Generate Files
              run: |
                  python _scripts/supportdocs_generator.py
            - name: Commit Files
              id: commit
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "github-actions"
                  git add --all
                  git status
                  if [ -z "$(git status --porcelain)" ]; then
                    echo "::set-output name=push::false"
                  else
                    git commit -m "Add generated data source" -a
                    echo "::set-output name=push::true"
                  fi
              shell: bash
            - name: Push Changes
              if: steps.commit.outputs.push == 'true'
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: main